# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeboard',
            name='desc',
            field=models.TextField(),
        ),
    ]
