# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_auto_20170827_2049'),
        ('frontpage', '0002_auto_20170827_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='summer_note_model',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('summer_field', django_summernote.fields.SummernoteTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
    ]
