# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20170830_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeboard',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='makeboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
