# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_auto_20170830_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeboard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
