# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20170830_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeboard',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='makeboard',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
